import { text } from './i18n';
import type { Lesson } from './content';
import type { MixSkill } from './mix-types';

export const mixSkillNames = {
  compression: text('Kompresyon', 'Compression'), attack: text('Attack / atak', 'Attack'), release: text('Release / bırakma', 'Release'),
  masking: text('Masking / örtüşme', 'Masking'), stereo: text('Stereo alan', 'Stereo field'),
  reverb: text('Reverb / yankı alanı', 'Reverb'), delay: text('Delay / tekrar', 'Delay'),
} satisfies Record<MixSkill, ReturnType<typeof text>>;
export const isAdvanced = (skill: string): skill is MixSkill => Object.hasOwn(mixSkillNames, skill);
export const needsStereo = (lesson: Lesson) => lesson.skill === 'stereo' || lesson.skill === 'delay' && lesson.level === 3;

const titles: Record<MixSkill, ReturnType<typeof text>[]> = {
  compression: [text('Kompresyonu duy', 'Hear compression'), text('Oranı karşılaştır', 'Compare ratios'), text('Miks içinde dinamikler', 'Dynamics in a mix')],
  attack: [text('İlk vuruşun kenarı', 'The edge of a hit'), text('Atak ve gövde', 'Attack & body'), text('İnce atak farkları', 'Subtle attack differences')],
  release: [text('Sesin geri dönüşü', 'The return of the sound'), text('Vuruşlar arasındaki nefes', 'Breathing between hits'), text('İnce bırakma farkları', 'Subtle release differences')],
  masking: [text('Melodiye yer aç', 'Make room for the melody'), text('Örtüşen frekanslar', 'Overlapping frequencies'), text('Küçük kesmeler, miks bağlamı', 'Small cuts in context')],
  stereo: [text('Solda, ortada, sağda', 'Left, centre, right'), text('Dar ve geniş', 'Narrow & wide'), text('Mono uyumluluğu', 'Mono compatibility')],
  reverb: [text('Ne kadar reverb?', 'How much reverb?'), text('Kuyruğun süresi', 'The length of the tail'), text('Ön gecikmeyi duy', 'Hear pre-delay')],
  delay: [text('Tekrarın zamanı', 'The timing of the echo'), text('Tekrarlar nasıl söner?', 'How do echoes fade?'), text('Ping-pong ve merkez', 'Ping-pong & centre')],
};

const descriptions: Record<MixSkill, ReturnType<typeof text>> = {
  compression: text('Ortalama seviyeleri eşit iki örnekte dinamik değişimi dinle.', 'Hear dynamic changes in two samples with matched average levels.'),
  attack: text('Kompresörün ilk vuruşa ne kadar hızlı tepki verdiğini duy.', 'Hear how quickly a compressor responds to the start of a hit.'),
  release: text('Kompresörün vuruştan sonra sesi nasıl serbest bıraktığını dinle.', 'Hear how a compressor lets go of the signal after a hit.'),
  masking: text('Hedef melodiyi tek başına tanı, ardından miks içinde karşılaştır.', 'Learn the target melody solo, then compare it in the mix.'),
  stereo: text('Konum, genişlik ve mono toplamını ayrı ayrı keşfet.', 'Explore position, width and the mono sum separately.'),
  reverb: text('Miktar, kuyruk ve ön gecikmeyi birer birer ayırt et.', 'Distinguish amount, tail length and pre-delay one at a time.'),
  delay: text('Tekrar aralığı, feedback ve stereo hareketi dinle.', 'Hear echo spacing, feedback and stereo movement.'),
};
function learn(skill: MixSkill, level: number) {
  if (skill === 'compression') return text(level === 1 ? 'Kompresör, eşik üstündeki bölümleri azaltır. Oran 1:1 ise kompresyon yoktur. Örnekler ortalama seviyede eşitlendiği için yüksekliğe değil, vuruş ile gövde arasındaki ilişkiye odaklan.' : level === 2 ? '2:1, 4:1 ve 8:1 oranlarını aynı eşik, atak ve bırakmayla karşılaştır. Oran büyüdükçe eşik üstündeki dinamikler daha fazla azalır. Bu oranlar her kaynakta aynı duyulmaz.' : 'A, 4:1 referans kompresyonudur. B’de yalnızca oran değişebilir. Bu kez A’ya göre daha az, aynı veya daha fazla sıkıştırmayı miks içinde ayırt et.', level === 1 ? 'A compressor reduces parts above its threshold. At 1:1 there is no compression. Average levels are matched, so focus on the relationship between hits and body.' : level === 2 ? 'Compare ratios of 2:1, 4:1 and 8:1 with the same threshold, attack and release. Higher ratios reduce dynamics above the threshold more. A ratio does not sound identical on every source.' : 'A is a 4:1 compressed reference. Only the ratio can change in B. Identify less, equal or more compression relative to A, in a mix.');
  if (skill === 'attack') return text('Attack, kompresörün azaltmayı ne kadar hızlı uyguladığını belirler. Hızlı atak ilk vuruşu daha fazla bastırabilir; yavaş atak ilk kenarı daha fazla geçirir. A aynı referanstır; B’de yalnızca atak süresi değişir. Bu eğitim motorundaki ms değerleri başka kompresörlerle birebir eşdeğer değildir.', 'Attack controls how quickly gain reduction is applied. A fast attack can suppress the start of a hit; a slower attack lets more of that edge through. A is a fixed reference; only attack changes in B. Millisecond values in this training model are not interchangeable with those on every compressor.');
  if (skill === 'release') return text('Release, azaltmanın ne kadar hızlı geri bırakıldığını belirler. Kısa bırakmada seviye daha çabuk döner; uzun bırakmada vuruşun sonrasında ve sonraki vuruşta azaltma sürebilir. Vuruşlar arasındaki gövdeyi dinle. Çok kısa veya uzun her durumda daha iyi demek değildir.', 'Release controls how quickly gain reduction recovers. With a short release the level returns sooner; a long release can keep reduction active after a hit and into the next one. Listen to the body between hits. Neither shorter nor longer is always better.');
  if (skill === 'masking') return text('İki kaynak benzer frekanslarda birbirini örtebilir. Burada hedef melodi sabit kalır; B’de yalnızca eşlik katmanının bir bölgesi azaltılır. “Melodiyi tek dinle” ile hedefi tanı, sonra A/B mikslerini karşılaştır. Her örtüşme sorun değildir; amaç bu hedefe yer açmaktır.', 'Two sources can mask each other in overlapping frequency regions. The target melody stays unchanged here; only one region of the backing layer is reduced in B. Learn the target with Solo melody, then compare the A/B mixes. Not every overlap is a problem; the goal here is room for this target.');
  if (skill === 'stereo') return [text('Pan, sesin sol ve sağ kanallardaki seviye ilişkisini değiştirir. A ortadadır; B’nin yerini bul. Stereo kulaklık kullan ve cihazındaki mono ses ayarını kapat.', 'Pan changes a sound’s level relationship between the left and right channels. A is centred; locate B. Use stereo headphones and disable your device’s mono audio setting.'), text('Genişlik, sol ve sağ arasındaki farkın miktarıyla ilişkilidir. Bu derste merkez bileşen korunur; yan bileşenin miktarı değişir. Konum ile genişlik ayrı özelliklerdir. Mono kontrolüyle merkez bileşeni tekrar dinleyebilirsin.', 'Width relates to the difference between left and right. This exercise preserves the mid component and changes the amount of side. Position and width are separate properties. Use the mono check to hear the mid again.'), text('Bir kanalın polaritesini ters çevirmek stereo toplamda sorun yaratabilir. A referanstır. B’yi Stereo ve Mono düğmeleriyle dinle: ortadaki ses mono toplamda korunuyor mu, iptal mi oluyor? Bu kasıtlı uç örnek mono kontrolünü öğretir.', 'Inverting one channel’s polarity can cause cancellation in the stereo sum. A is the reference. Listen to B with Stereo and Mono: does the centred sound survive the mono sum or cancel? This deliberately extreme example teaches the mono check.')][level - 1];
  if (skill === 'reverb') return [text('Reverb, yoğun yansımalarla bir kuyruk oluşturur. Burada süre sabittir; sadece eklenen reverb miktarı değişir. A kaynak sestir, B’de az veya çok reverb vardır. Son vuruştan sonra kalan sesi dinle.', 'Reverb creates a tail of dense reflections. Duration is fixed here; only the added reverb amount changes. A is the source; B has less or more reverb. Listen after the last hit.'), text('Decay, reverb kuyruğunun sönme süresini belirler. Miktar ve ön gecikme sabitken 0.5, 1.5 ve 3 saniyelik nominal kuyrukları karşılaştır. Bunlar eğitim motoru değerleridir; gerçek oda büyüklüğünü ölçmez.', 'Decay controls how long the reverb tail fades. Compare nominal tails of 0.5, 1.5 and 3 seconds with amount and pre-delay fixed. These are training model values, not measurements of room size.'), text('Pre-delay, kuru ses ile reverbün başlangıcı arasına eklenen beklemedir. Süre ve miktar aynı kalır; 0, 30 veya 80 ms ek ön gecikme değişir. İlk vuruş ile yansımaların ayrılmasını dinle.', 'Pre-delay adds a wait between the dry sound and the start of the reverb. Duration and amount stay fixed; added pre-delay is 0, 30 or 80 ms. Listen for separation between the hit and its reflections.')][level - 1];
  return [text('Delay ayrı tekrarlar üretir. 120 BPM’de 125 ms onaltılık, 250 ms sekizlik ve 500 ms bir vuruştur. A kaynak sestir; B’de tekrar aralığını dinle. Kuyruğu dinlemek için döngünün sonundaki boşluğu kullan.', 'Delay creates distinct echoes. At 120 BPM, 125 ms is a sixteenth note, 250 ms an eighth and 500 ms a beat. A is the source; listen for the echo spacing in B. Use the gap at the end of the loop to hear the tail.'), text('Feedback, önceki tekrarın ne kadarının yeniden tekrarlandığını belirler. Zaman ve miktar sabittir. Düşük feedback daha çabuk söner, yüksek feedback daha çok tekrar bırakır.', 'Feedback determines how much of an echo feeds the next repetition. Time and amount are fixed. Low feedback fades sooner; high feedback leaves more echoes.'), text('Merkez delay tekrarları ortada tutar. Ping-pong delay tekrarları sol ve sağ arasında dağıtır. Zaman, feedback ve toplam seviye aynı tutulur. Stereo kulaklıkla tekrarların yerini takip et.', 'A centred delay keeps echoes in the middle. Ping-pong delay distributes them between left and right. Time, feedback and overall level are held constant. Follow the echoes with stereo headphones.')][level - 1];
}
export const advancedLessons: Lesson[] = (Object.keys(mixSkillNames) as MixSkill[]).flatMap(skill => [1, 2, 3].map(level => ({
  id: `${skill}-${level}`, path: 'mix', skill, level, title: titles[skill][level - 1], description: descriptions[skill], learn: learn(skill, level),
  listen: text('Önce A referansını, sonra B’yi dinle. Aynı zaman çizgisinde geçiş yap; değişimi seç. Yanlış yanıtından sonra C, seçtiğin ayarın nasıl duyulduğunu gösterir.', 'Listen to reference A, then B. Switch on the same timeline and choose the change. After a wrong answer, C lets you hear the setting you chose.'),
  tip: skill === 'masking' ? text('Önce solo hedefi, sonra miksin bütününü dinle. Bu kesme her miks için önerilen bir reçete değildir.', 'Hear the solo target first, then the whole mix. This cut is not a prescription for every mix.') : text('A/B/C ortalama seviyeleri eşitlenir. Kulaklıkla rahat seviyede dinle; ayarlar tek değişkenli eğitim örnekleridir. Kendi Kaydın alanında serbestçe deneyebilirsin.', 'Average A/B/C levels are matched. Use headphones at a comfortable volume; settings are examples with one variable changed. Explore freely in Your recording.'),
})));
