import { text } from './i18n';
import type { ExamCourseId, ExamProfile } from './exam-types';

export const examCourses: { id: ExamCourseId; title: ReturnType<typeof text>; intro: ReturnType<typeof text>; steps: ReturnType<typeof text>[]; checks: ReturnType<typeof text>[]; practices: string[][] }[] = [
  { id: 'pitch', title: text('Tek ses ve aralık tekrarı', 'Pitch and interval reproduction'), intro: text('Sesi rahat bir heceyle geri söyle. Ses aralığın dışındaysa oktavını değiştir; zorlamadan çalış.', 'Sing the pitch back on a comfortable syllable. Move it by an octave if needed; work within your range.'), steps: [text('Önce tek sesi dinle ve zihninde tut. Ses kesilince “na” ile söyle.', 'Listen to one note and hold it in mind. Sing “na” when it stops.'), text('İki sesli örnekte ilk sesi sabitle, sonra aralığın yönünü ve mesafesini koru.', 'Anchor the first note of a pair, then preserve the direction and distance.'), text('Kontrol için örneği yeniden dinle. Öğretmeninle entonasyonu değerlendir.', 'Replay to check. Review intonation with your teacher.')], checks: [text('Başlangıç sesini korudum.', 'I retained the starting pitch.'), text('Sesler arasındaki mesafeyi korudum.', 'I retained the distance between notes.'), text('Sesimi zorlamadan tamamladım.', 'I finished without straining my voice.')], practices: [['direction-1','degree-1'],['interval-2','degree-2'],['interval-2','degree-3']] },
  { id: 'polyphony', title: text('İki, üç ve dört ses', 'Two, three and four voices'), intro: text('Birlikte çalınan sesleri, pes sesten tize doğru tek tek söylemeyi çalış.', 'Practise singing simultaneously played notes separately, from lowest to highest.'), steps: [text('İlk dinlemede dış sesleri bul. İkinci dinlemede aradaki seslere odaklan.', 'Find the outer voices first, then focus on the inner voices.'), text('Sesler kesilince pes sesten başla. Her sesi ayrı bir “na” ile söyle.', 'When the sound stops, start from the lowest note and sing each on “na”.'), text('Akorun niteliğini tanımak bir destek çalışmasıdır; sesleri tek tek söylemenin yerini tutmaz.', 'Identifying chord quality supports practice; it does not replace singing individual voices.')], checks: [text('Pes sesi buldum.', 'I found the lowest voice.'),text('Ara sesleri atlamadım.', 'I included the inner voices.'),text('Ses sırasını korudum.', 'I retained the voice order.')], practices: [['chord-3'],['chord-3'],['chord-3']] },
  { id: 'melody', title: text('Ezgi hafızası ve tekrar', 'Melodic memory and reproduction'), intro: text('Melodiyi küçük gruplar halinde zihninde tut; sesleri aynı sırayla geri söyle.', 'Remember a melody in small groups and sing the notes back in order.'), steps: [text('Örneği dinlerken ilk ses ve melodinin hareketini takip et.', 'Track the first note and the melodic contour.'),text('Ses kesilince aynı tempoda geri söyle. Önce doğruluk, ardından akıcılık.', 'Sing it back at the same tempo. Work on accuracy, then fluency.'),text('A/B hafıza pratiği değişimi ayırt etmeyi ölçer. Vokal tekrarını öğretmeninle kontrol et.', 'A/B memory practice measures change detection. Check vocal reproduction with your teacher.')], checks: [text('İlk ve son sesi korudum.', 'I retained the first and final pitches.'),text('Nota sırasını korudum.', 'I retained the note order.'),text('Duraksamadan tamamladım.', 'I finished without hesitation.')], practices: [['memory-1','melodic-dictation-1'],['memory-2','melodic-dictation-2'],['memory-3','melodic-dictation-3']] },
  { id: 'rhythm', title: text('Ritim hafızası ve tekrar', 'Rhythmic memory and reproduction'), intro: text('Vuruşu koruyarak ritmi alkışla veya masa üzerinde tekrar et.', 'Clap or tap the rhythm while keeping the beat steady.'), steps: [text('Dört sayımla tempoyu yerleştir; örneği dinlerken içinden say.', 'Establish the tempo with four counts and count silently through the pattern.'),text('Suslarda da vuruşu sürdür. Kısa sesleri ayrı birer vuruş sanma.', 'Keep the beat through rests. Avoid treating every short note as a new beat.'),text('Dokunma pratiğinde zamanlama geri bildirimi al; sınavın sözlü tekrarını ayrıca prova et.', 'Use tapping practice for timing feedback, then rehearse the oral exam format separately.')], checks: [text('Temposunu korudum.', 'I retained the tempo.'),text('Susları korudum.', 'I retained the rests.'),text('Vuruş bölünmelerini korudum.', 'I retained the subdivisions.')], practices: [['rhythm-repeat-1','rhythmic-dictation-1'],['rhythm-repeat-2','rhythmic-dictation-2'],['rhythm-repeat-3','rhythmic-dictation-3']] },
  { id: 'dictation', title: text('Melodik ve ritmik dikte', 'Melodic and rhythmic dictation'), intro: text('İlk dinlemede bütününü anla, sonraki dinlemelerde ayrıntıları tamamla.', 'Understand the whole phrase first, then fill in details on later hearings.'), steps: [text('Tonal merkezi ve ölçüyü belirle. Ezgiyi içinden söyle; ritmi ayrı takip et.', 'Identify the tonal centre and metre. Hear the melody internally and track rhythm separately.'),text('Uygulamada dereceleri ve vuruş konumlarını yaz. Yanlış konumları düzeltip tekrar dinle.', 'Enter degrees and beat positions in the app. Correct misplaced entries and listen again.'),text('Kâğıtta anahtar, donanım, süre ve ölçü çizgileriyle yazmayı ayrıca çalış. Buradaki derece/ızgara girişi tam nota diktesi değildir.', 'Also practise writing clefs, key signatures, durations and barlines on paper. Degree/grid entry here is not full staff dictation.')], checks: [text('Tonal merkezi korudum.', 'I retained the tonal centre.'),text('Sesleri ve susları doğru yerleştirdim.', 'I placed pitches and rests correctly.'),text('Yanıtımı ölçüyle kontrol ettim.', 'I checked my answer against the metre.')], practices: [['melodic-dictation-1','rhythmic-dictation-1'],['melodic-dictation-2','rhythmic-dictation-2'],['melodic-dictation-3','rhythmic-dictation-3']] },
  { id: 'sight-reading', title: text('Deşifre ve solfej', 'Sight-reading and solfège'), intro: text('Önce sessizce incele, ardından eşit vuruşlarla nota adlarını söyle.', 'Inspect the score silently, then sing note names with steady beats.'), steps: [text('Anahtar, donanım ve ölçüyü oku. Başlangıç sesiyle tonal merkezi kur.', 'Read the clef, key signature and metre. Establish the tonal centre from the starting pitch.'),text('Zor atlamaları içinden duy; vuruşu durdurmadan devam et.', 'Hear difficult leaps internally and continue without stopping the beat.'),text('Önce örneği dinlemeden söyle; sonra kayıtla karşılaştır. Bu örnekler Do majör ve 4/4 ile sınırlıdır.', 'Sing before hearing the example, then compare with playback. These examples are limited to C major and 4/4.')], checks: [text('Nota adlarını doğru okudum.', 'I read the note names correctly.'),text('Entonasyonu korudum.', 'I retained intonation.'),text('Ölçü boyunca akışı sürdürdüm.', 'I maintained the flow through the bars.')], practices: [['degree-1'],['degree-2','function-2'],['degree-3','function-3']] },
  { id: 'performance', title: text('Eser ve jüri provası', 'Performance and jury rehearsal'), intro: text('Hazırladığın eseri kesintisiz sun; teknik doğrulukla müzikal anlatımı birlikte değerlendir.', 'Present your prepared work without interruption; review technique and musical expression together.'), steps: [text('Hedef programın güncel repertuvar, eser sayısı, eşlik ve ezber koşullarını resmî kılavuzdan kontrol et.', 'Check your programme’s current repertoire, number of works, accompaniment and memorisation requirements.'),text('Eser adını ve besteciyi söyle, başlangıç temponu zihninde kur, sonra başla.', 'State the work and composer, establish the tempo internally, then begin.'),text('Hata olduğunda başa dönmeden sürdür. Sonrasında öğretmeninle üslup, teknik ve ifade üzerine konuş.', 'Continue after mistakes without restarting. Review style, technique and expression with your teacher.')], checks: [text('Eseri kesintisiz sundum.', 'I presented the work without restarting.'),text('Tempo ve cümleleme tutarlıydı.', 'Tempo and phrasing were consistent.'),text('Repertuvar koşullarını kontrol ettim.', 'I checked the repertoire requirements.')], practices: [['memory-1'],['memory-2'],['memory-3']] },
];

const commonLessons = [
  ['memory-1','rhythmic-dictation-1','degree-1','chord-3','melodic-dictation-1','memory-1'],
  ['memory-2','interval-2','rhythmic-dictation-2','chord-3','melodic-dictation-2','degree-2','memory-2','rhythmic-dictation-2'],
  ['memory-3','interval-2','chord-3','rhythmic-dictation-3','melodic-dictation-3','degree-3','memory-3','interval-2','melodic-dictation-3','rhythmic-dictation-3'],
];
export const examProfiles: ExamProfile[] = [{ id: 'common', title: text('Ortak hazırlık', 'Common preparation'), program: text('İşitme ve müzikal beceriler', 'Aural and musical skills'), summary: text('Tek ve çok ses, ezgi, ritim, dikte, solfej ve icrayı düzenli çalış.', 'Practise pitches, chords, melody, rhythm, dictation, solfège and performance.'), sources: [], scope: examCourses.map(c => ({title:c.title, detail:c.intro, courses:[c.id]})), lessons: commonLessons, limits: text('Bu profil bir kurumun resmî sınav şablonu değildir. Deneme; seçmeli, derece ve ritim ızgarası yanıtlarıyla yapılan Freq işitme uyarlamasıdır. Söyleme, icra ve tam nota diktesi ayrıca öğretmen/jüri ile değerlendirilir.', 'This profile is not an official institutional exam template. The mock is a Freq aural adaptation using choices, degrees and a rhythm grid. Singing, performance and full staff dictation require separate teacher/jury assessment.') }];
export const getExamProfile = (id: string) => examProfiles.find(p => p.id === id);
export const mockSecondsPerQuestion = 60;
export const mockListenLimit = 3;

export const courseLevelFocus: Record<ExamCourseId, ReturnType<typeof text>[]> = {
  pitch: [text('Tek sesi zihninde tut ve rahat heceyle geri söyle.', 'Retain a single pitch and sing it back on a comfortable syllable.'),text('Yukarı çıkan iki sesi aralıklarını koruyarak tekrar et.', 'Reproduce two ascending pitches while retaining their interval.'),text('İnen, geniş ve küçük aralıkları ayrı ayrı tekrar et.', 'Reproduce descending, wide and small intervals.')],
  polyphony: [text('İki eşzamanlı sesi pes–tiz sırasıyla ayır.', 'Separate two simultaneous voices from low to high.'),text('Üç sesin orta sesini atlamadan tekrar et.', 'Reproduce three voices without missing the middle one.'),text('Dört sesin iç seslerini ve sırasını koru.', 'Retain the inner voices and order of four pitches.')],
  melody: [text('Dört notayı yönleriyle ve başlangıç sesiyle hatırla.', 'Remember four notes with their contour and starting pitch.'),text('Altı notayı küçük gruplar halinde zihninde tut.', 'Retain six notes in small groups.'),text('Sekiz notalı ezgiyi akışını kesmeden tekrar et.', 'Reproduce an eight-note melody without breaking its flow.')],
  rhythm: [text('Dörtlük vuruşları sabit tempoda tekrar et.', 'Reproduce quarter-note hits at a steady tempo.'),text('Sekizlik bölünmeleri ve boşlukları koru.', 'Retain eighth-note subdivisions and gaps.'),text('Onaltılık konumları vuruşu kaybetmeden tekrar et.', 'Reproduce sixteenth-note positions without losing the beat.')],
  dictation: [text('Kısa, az dereceli ezgiyi ve dörtlük ritmi ayrı yaz.', 'Write a short melody with few degrees and a quarter-note rhythm separately.'),text('Daha uzun ezgi ve sekizlik konumlarda ayrıntıları tamamla.', 'Fill in details of a longer melody and eighth-note positions.'),text('Susları ve onaltılık konumları da kontrol et; kâğıtta tam notasyonla ek çalışma yap.', 'Check rests and sixteenth-note positions; add full notation practice on paper.')],
  'sight-reading': [text('Bir ölçülük yakın hareketi nota adlarıyla söyle.', 'Sing one bar of nearby movement with note names.'),text('İki ölçüyü vuruşu durdurmadan oku.', 'Read two bars without stopping the beat.'),text('İki ölçüde geniş atlamaları önceden içinden duy.', 'Hear wider leaps internally across two bars.')],
  performance: [text('Bir kısa cümleyi temiz başlangıç ve bitirişle sun.', 'Present one short phrase with a clear beginning and ending.'),text('Bir eseri kesintisiz çal/söyle; tempo ve ifadeyi değerlendir.', 'Play/sing one work without interruption and review tempo and expression.'),text('Hedefinin doğrulanmış repertuvar koşullarıyla bütün programı bir öğretmene sun.', 'Present the full programme to a teacher using your target’s verified repertoire requirements.')],
};
